### ISSUE TITLE
How to run on custom images and clothing

### ISSUE THREAD

**Issue by dev20111** [fyviezhao/M3D-VTON#1]
Can you please let me know how to create custom data for testing?
I see this has many files mpv3d_example.
Also does your code hav anything to do with SMPL 
I assume the end result is just the  3d model with no SMPL and with poses 
Correct?

**Comment by fyviezhao** [comment]
Hi, I have updated the README, and please refer there for testing on custom data. Our code has nothing to do with SMPL, thus your assumption is correct.
