### ISSUE TITLE
depth generate

### ISSUE THREAD

**Issue by hematank** [fyviezhao/M3D-VTON#3]
hi，thans for your great job. i am very curious about this project and how to generate depth. Is there some code to refer. hope your reply!

**Comment by fyviezhao** [comment]
Hi, great to hear that you like our job :). The double depth maps used in this code are orthographically projected from the PIFu-HD meshes fitted on the MPV3D person images. We provide the detailed camera setting in the `mpv3d_example` folder and you may also want to have a look at the `rgbd2pcd.py` for the unprojection process.

**Comment by fyviezhao** [comment]
Hi, great to hear that you like our work :). The double depth maps used in this code are orthographically projected from the PIFu-HD meshes fitted on the MPV3D person images. We provide the detailed camera setting in the `mpv3d_example` folder and you may also want to look at the `rgbd2pcd.py` for the unprojection process.
