### ISSUE TITLE
DRM and TFM

### ISSUE THREAD

**Issue by hematank** [fyviezhao/M3D-VTON#4]
thanks for your reply.  this is great job! i have another question that what's the DRM and TFM's network? i can't find any detailed description in papers. are they using gan network? what can i refer to. i look forward to your reply, thank u.

**Comment by fyviezhao** [comment]
Hi hematank, you are welcome. The DRM and the TFM are the abbreviations for the Depth Refinement Module and the Texture Fusion Module respectively. You can find a detailed description of these two modules in Section 3.2 and Section 3.3 of our paper. Both of them use a UNet-like network without adversarial training.
