### ISSUE TITLE
warp cloth 

### ISSUE THREAD

**Issue by hematank** [fyviezhao/M3D-VTON#5]
I 'm sorry to bother you again. You are so kind-hearted, thank you again. 
I just happened the probelm that warp cloth saved by MTM model seems smaller when i train MTM in MPV3D Dataset with the same param configures. But the warp cloth generated by your pretrained MTM model is larger. I analysis for a long time, but i can't find the reason.  Please help me! Best wish with you.

**Comment by fyviezhao** [comment]
Hi hematank, you are welcome. Have you preprocessed the MPV3D data before training MTM? It will affect the garment warping process since we use a two-stage garment-person alignment strategy, where the first stage is performed offline during the data preprocessing (of course it can also be done online). With the preprocessed data and the default params configuration, it should have no problem to train MTM and generate the same result as the pretrained model does.

**Comment by hematank** [comment]
I have processed the MPV3D data before training MTM and check the pre-aligned cloth is ok. But When I train MTM with the default params configuration and use the model to test MTM, the warp cloth seems abnormal.  Does github can upload picture？I can't find any access to upload the abnormal picture.

**Comment by fyviezhao** [comment]
Hi, guess you use WeChat, right? It would be easier if we use it to upload images and have some instant discussion. May you consider emailing me (zhaofw939@gmail.com) your WeChat number and I will add you as soon as I can.  Hopefully we can solve your questions more quickly on WeChat, and then summarize the key points here in this issue. Thanks : )

**Comment by fyviezhao** [comment]
Hi, guess you use WeChat, right? It would be easier if we use it to upload images and have some instant discussion. Will you please consider emailing me (zhaofw939@gmail.com) your WeChat number and I will add you as soon as I can.  Hopefully we can solve your questions more quickly on WeChat, and then summarize the key points here in this issue. Thanks : )

**Comment by hematank** [comment]
ok，i emailed my wechat id just now. Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月26日(星期天) 晚上8:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fyviezhao/M3D-VTON] warp cloth  (#5)





 
Hi, guess you use WeChat, right? It would be easier if we use it to upload images and have some instant discussion. May you consider emailing me ***@***.***) your WeChat number and I will add you as soon as I can.  Hopefully we can solve your questions more quickly on WeChat, and then summarize the key points here in this issue. Thanks : )
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hematank** [comment]
It's my fault! I found I didn't train MTM with 100 epoches. Maybe it can't conver well. Now the warp cloth saved by MTM model seems ok when trained with 100 epoches. Sorry for my fault! Thank u a lot.

**Comment by fyviezhao** [comment]
You are welcome. Closed.

**Comment by hcy1998** [comment]
> I 'm sorry to bother you again. You are so kind-hearted, thank you again. I just happened the probelm that warp cloth saved by MTM model seems smaller when i train MTM in MPV3D Dataset with the same param configures. But the warp cloth generated by your pretrained MTM model is larger. I analysis for a long time, but i can't find the reason. Please help me! Best wish with you.


> I 'm sorry to bother you again. You are so kind-hearted, thank you again. I just happened the probelm that warp cloth saved by MTM model seems smaller when i train MTM in MPV3D Dataset with the same param configures. But the warp cloth generated by your pretrained MTM model is larger. I analysis for a long time, but i can't find the reason. Please help me! Best wish with you.
Did you encountered this problem during training MTM?
![image](https://user-images.githubusercontent.com/48088535/154001812-0bf1c554-0524-44af-8e81-fd0ae8a1b63f.png)
